name: Feature Request
description: Request a new feature
title: '[Feature Request]: '
labels: ['enhancement']
assignees:
  - m-scott-lassiter
body:
  - type: markdown
    attributes:
      value: |
        Thank you taking the time to fill out this request!
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the problem you have and what feature addition would help address it?
      placeholder: Right now, I am trying to ___. I would like the tool to ___.
    validations:
      required: true
  - type: dropdown
    id: contribute
    attributes:
      label: Are you able/willing to make the change? (It's ok if you're not!)
      multiple: false
      options:
        - 'No'
        - 'Yes'
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      options:
        - label: I agree to follow this project's [Code of Conduct](https://github.com/M-Scott-Lassiter/jest-geojson/blob/main/CODE_OF_CONDUCT.md)
          required: true
