name: New Matcher Request
description: Request a new feature
title: '[New Matcher Request]: '
labels: ['new matcher']
assignees:
  - m-scott-lassiter
body:
  - type: markdown
    attributes:
      value: |
        Thank you taking the time to fill out this request!
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Give an overview of this matcher and why it is necessary. Include links for citations.
    validations:
      required: true
  - type: textarea
    id: tests
    attributes:
      label: Tests
      description: What tests will be required to verify this behavior works correctly? Include both passing and failing behaviors.
    validations:
      required: true
  - type: dropdown
    id: contribute
    attributes:
      label: Are you able/willing to make the change? (It's ok if you're not!)
      multiple: false
      options:
        - 'No'
        - 'Yes'
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      options:
        - label: I agree to follow this project's [Code of Conduct](https://github.com/M-Scott-Lassiter/jest-geojson/blob/main/CODE_OF_CONDUCT.md)
          required: true
