# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main, next]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 16.x, 17.x, 18.x]
        os: [ubuntu-latest, windows-latest, macos-latest]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Clean Install
        run: npm ci
        # The FORCE_COLOR is required because tests were failing in Github due to the snapshots.
        # See: https://stackoverflow.com/questions/72311493/jest-snapshots-causing-github-action-tests-to-fail
      - name: Test
        run: npm run test
        env:
          FORCE_COLOR: true
